server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/security_jwt
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

jwt:
  secret: "3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b"
  expiration: 86400000      # 24h en milisegundos
  refresh-expiration: 604800000  # 7 días

logging:
  level:
    org.springframework.security: TRACE  