server:
  port: 8083

spring:
  application:
    name: module-cognito

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_DhRbMOtES

cognito:
  client-id: 5c95rig78hosnve1he3das2bp3
  region: us-east-1
  user-pool-id: us-east-1_DhRbMOtES

logging:
  level:
    org.springframework.security: DEBUG